### PR TITLE
Update to juttle 0.2.0:

### PR DESCRIPTION
**Pull request by mstemm**
- Update package.json
- The base class for the read proc should be source. Fix that.
- Start using the new RT-MISSING-TIME-RANGE-ERROR that was added in 0.2.0.

@demmer @go-oleg @bkutil

### CODE REVIEW

**Comment by demmer** [comment]
Other than the fact that this should be 3 separate commits, lgtm.

**Comment by mstemm** [comment]
Can you take a second look at the additional changes?

**Comment by demmer** [comment]
The changes in a878001 seem unrelated to juttle 0.2.0, right?

The version bump in 822cb16 shouldn't be done on this branch -- `cut-release` will do it for you right before it pushes.

Also at this point you should really redo the commit history to keep the three high-level changes above separated and remove the lint commit, etc.

**Comment by demmer** [comment]
looks good -- thanks

**Pull request merged**
